import {createClient} from "@supabase/supabase-js";
import OpenAI from "openai";
const SUPABASE_URL=process.env.SUPABASE_URL, ANON=process.env.SUPABASE_ANON_KEY, SERVICE=process.env.SUPABASE_SERVICE_ROLE_KEY, MODEL=process.env.OPENAI_MODEL||"gpt-5-mini";
const admin=createClient(SUPABASE_URL,SERVICE,{auth:{autoRefreshToken:false,persistSession:false}});
const openai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
const j=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json"}});
async function auth(req){const h=req.headers.get("authorization")||"";if(!h.startsWith("Bearer "))throw Error("AUTH_REQUIRED");const {data,error}=await createClient(SUPABASE_URL,ANON).auth.getUser(h.slice(7));if(error||!data.user)throw Error("AUTH_INVALID");return data.user}
async function workspace(user){let {data,error}=await admin.from("workspace_members").select("workspace_id,role,workspaces(id,name,plan)").eq("user_id",user.id).single();if(error){const {data:w}=await admin.from("workspaces").insert({name:"My Agronomy Workspace",plan:"PUBLIC"}).select().single();if(w){await admin.from("workspace_members").insert({workspace_id:w.id,user_id:user.id,role:"owner"});return {id:w.id,name:w.name,plan:w.plan,role:"owner"}}throw Error("WORKSPACE_NOT_READY")}return {...data.workspaces,id:data.workspace_id,role:data.role}}
function risk(b,finding=""){let s=0,r=[];const text=(finding+" "+(b.soil_status||"")).toLowerCase();if(Number(b.avg_ph)<4.5){s+=30;r.push("pH sangat masam")}if(text.includes("kering")){s+=20;r.push("indikasi kering")}if(Number(b.rainfall_mm)<100){s+=15;r.push("curah hujan rendah")}if(Number(b.avg_attack_pct)>=15){s+=35;r.push("serangan >=15%")}else if(Number(b.avg_attack_pct)>5){s+=18;r.push("serangan perlu monitoring")}s=Math.min(100,s);return {score:s,level:s>=60?"HIGH":s>=30?"MEDIUM":"LOW",reasons:r}}
function prompt(kb){return `Anda adalah AI Agronomy Engine untuk kelapa sawit. Anda membantu pengguna mengambil keputusan berbasis data, bukan menggantikan agronomis. Aturan: (1) bedakan OBSERVATION, ANALYSIS, RECOMMENDATION; (2) jangan mengklaim diagnosis pasti dari satu foto; (3) jangan mengarang dosis pupuk/pestisida, threshold resmi, atau persyaratan sertifikasi; (4) jika sumber/data kurang, gunakan NEED FIELD VERIFICATION; (5) prioritaskan SOP/GAP yang diberikan dalam knowledge base; (6) sebutkan sumber knowledge yang dipakai; (7) rekomendasi harus dapat diverifikasi. Knowledge base workspace: ${JSON.stringify(kb)}`}
async function kbFor(ws,query){const {data}=await admin.from("knowledge_base").select("title,source,category,content").eq("workspace_id",ws.id).limit(50);return data||[]}
async function route(req){const u=new URL(req.url);if(u.pathname==="/api/config")return j({url:URL,anon:ANON});const user=await auth(req),ws=await workspace(user),p=u.pathname;
if(p==="/api/state"){const [b,m,a,h,k]=await Promise.all([admin.from("blocks").select("*").eq("workspace_id",ws.id).order("block_code"),admin.from("maintenance_records").select("id",{count:"exact",head:true}).eq("workspace_id",ws.id),admin.from("actions").select("*").eq("workspace_id",ws.id).neq("status","Closed").order("created_at",{ascending:false}).limit(20),admin.from("analyses").select("id",{count:"exact",head:true}).eq("workspace_id",ws.id).gte("risk_score",60),admin.from("knowledge_base").select("id",{count:"exact",head:true}).eq("workspace_id",ws.id)]);return j({workspace:ws,blocks:b.data||[],maintenance_count:m.count||0,open_actions:a.data?.length||0,high_risk:h.count||0,actions:a.data||[],knowledge_count:k.count||0,ai_enabled:!!openai})}
if(p==="/api/blocks"&&req.method==="POST"){const x=await req.json();if(!x.block_code)throw Error("Blok wajib diisi");const {data,error}=await admin.from("blocks").upsert({...x,workspace_id:ws.id,owner_id:user.id},{onConflict:"workspace_id,block_code"}).select().single();if(error)throw Error(error.message);return j(data)}
if(p==="/api/maintenance"&&req.method==="POST"){const x=await req.json();if(!x.block_code)throw Error("Blok wajib diisi");const {data,error}=await admin.from("maintenance_records").insert({...x,workspace_id:ws.id,owner_id:user.id}).select().single();if(error)throw Error(error.message);return j(data)}
if(p==="/api/actions"&&req.method==="GET"){const {data,error}=await admin.from("actions").select("*").eq("workspace_id",ws.id).order("created_at",{ascending:false});if(error)throw Error(error.message);return j({actions:data||[]})}
if(p.startsWith("/api/actions/")&&req.method==="PATCH"){const id=p.split("/").pop();const x=await req.json();const {data,error}=await admin.from("actions").update(x).eq("id",id).eq("workspace_id",ws.id).select().single();if(error)throw Error(error.message);return j(data)}
if(p==="/api/knowledge"&&req.method==="GET"){const {data,error}=await admin.from("knowledge_base").select("*").eq("workspace_id",ws.id).order("created_at",{ascending:false});if(error)throw Error(error.message);return j({knowledge:data||[]})}
if(p==="/api/knowledge"&&req.method==="POST"){if(!["owner","admin"].includes(ws.role))throw Error("Hanya owner/admin dapat menambah knowledge.");const x=await req.json();if(!x.title||!x.content)throw Error("Judul dan isi wajib.");const {data,error}=await admin.from("knowledge_base").insert({...x,workspace_id:ws.id,created_by:user.id}).select().single();if(error)throw Error(error.message);return j(data)}
if(p==="/api/chat"&&req.method==="POST"){if(!openai)throw Error("AI belum dikonfigurasi. Tambahkan OPENAI_API_KEY.");const x=await req.json(),kb=await kbFor(ws,x.question||"");let block=null;if(x.block_id){const z=await admin.from("blocks").select("*").eq("id",x.block_id).eq("workspace_id",ws.id).single();block=z.data}const rr=risk(block||{},x.question||"");const resp=await openai.responses.create({model:MODEL,input:[{role:"system",content:prompt(kb)},{role:"user",content:`Pertanyaan: ${x.question}\nBlok: ${JSON.stringify(block)}\nRisk engine: ${JSON.stringify(rr)}\nJawab dalam bahasa Indonesia. Berikan: ringkasan, data yang mendukung, kemungkinan penyebab, tindakan segera yang aman, verifikasi, dan sumber knowledge.`}]});return j({status:"AI RESPONSE",answer:resp.output_text,sources:kb.map(k=>k.title).join(", ")||"Belum ada knowledge workspace"})}
if(p==="/api/analyze"&&req.method==="POST"){if(!openai)throw Error("AI belum dikonfigurasi. Tambahkan OPENAI_API_KEY.");const fd=await req.formData(),bid=fd.get("block_id"),parameter=fd.get("parameter"),finding=fd.get("finding")||"",img=fd.get("image");const {data:b,error:be}=await admin.from("blocks").select("*").eq("id",bid).eq("workspace_id",ws.id).single();if(be)throw Error(be.message);const rr=risk(b,finding),kb=await kbFor(ws,parameter);let content=[{type:"input_text",text:`Blok=${JSON.stringify(b)}\nParameter=${parameter}\nTemuan=${finding}\nRisk=${JSON.stringify(rr)}\nKnowledge=${JSON.stringify(kb)}\nKeluarkan JSON: finding,cause,recommendation,verification_status,source_note`}];if(img?.type?.startsWith("image/")){const buf=Buffer.from(await img.arrayBuffer());content.push({type:"input_image",image_url:`data:${img.type};base64,${buf.toString("base64")}`,detail:"high"})}const resp=await openai.responses.create({model:MODEL,input:[{role:"system",content:prompt(kb)},{role:"user",content}]});let o;try{o=JSON.parse(resp.output_text)}catch{o={finding:resp.output_text,cause:"",recommendation:"Verifikasi lapangan sesuai SOP/GAP.",verification_status:"NEED FIELD VERIFICATION",source_note:"Output AI perlu diverifikasi."}}const an={workspace_id:ws.id,owner_id:user.id,block_id:bid,parameter,finding:o.finding||finding,cause:o.cause||"",recommendation:o.recommendation||"",verification_status:o.verification_status||"NEED FIELD VERIFICATION",source_note:o.source_note||"",risk_score:rr.score,risk_level:rr.level,ai_model:MODEL};const {data:a,error:ae}=await admin.from("analyses").insert(an).select().single();if(ae)throw Error(ae.message);await admin.from("actions").insert({workspace_id:ws.id,owner_id:user.id,block_id:bid,analysis_id:a.id,block_code:b.block_code,priority:rr.level,finding:an.finding,action_text:an.recommendation,pic:"",status:"Open"});if(img?.type?.startsWith("image/")){const ext=(img.name||"jpg").split(".").pop();const path=`${ws.id}/${a.id}.${ext}`;const {error:up}=await admin.storage.from("evidence").upload(path,Buffer.from(await img.arrayBuffer()),{contentType:img.type,upsert:false});if(!up)await admin.from("evidence").insert({workspace_id:ws.id,owner_id:user.id,analysis_id:a.id,storage_path:path,file_name:img.name,file_type:img.type})}return j({...an,id:a.id,risk_reasons:rr.reasons})}
return j({error:"Not found"},404)}
export default async req=>{try{return await route(req)}catch(e){return j({error:e.message},e.message.includes("AUTH")?401:400)}};export const config={path:"/api/*"};
